---
- hosts: localhost
  vars:
    github_repo_url: https://Shivam-atd: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@github.com/Ataloud-Projects/ataloudsite.git
    branch_name: test-openshift
    date: "{{ lookup('pipe', 'date +%F') }}"
  collections:
    - kubernetes.core
  tasks:
    - name: Get a list of all pods from any namespace
      kubernetes.core.k8s_info:
        kind: Pod
        namespace: ansible-ataloud
      register: pod_list
    - name: Create latest directory
      shell: mkdir -p /tmp/shivam-{{ date }}
    - name: permission to directory
      shell: chmod 777  /tmp/shivam-{{ date }}
    - name: Clone the repository
      git:
        repo: "{{ github_repo_url }}"
        dest: /tmp/shivam-{{ date }}
        version: "{{ branch_name }}"
      register: git_clone_result
    - name: Print git clone output
      debug:
        var: git_clone_result
    - name: create build directory
      file:
        path: /tmp/shivam-{{ date }}
        state: directory
        owner: root
        group: root
        mode: "0755"
    - name: installing podman
      package:
        name: podman
        state: present
